## Choropleth Map of Temperatures across the US

This will teach you how to make a choropleth map from different data of the US with python's geopandas. 
A choropleth is a map that uses colors to shade different data based on its value.

In [1]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import geopandas

In [2]:
demo = pd.read_csv("data/CtyAvDemog2010.csv",delimiter=',', skiprows=0, low_memory=False, encoding='latin-1')
demo

,OBJECTID,STATEFP,COUNTYFP,GEOID,NAME,Lat,Lon,Avg_PercentBlackorAfricanAmericanalone,Avg_PercentAmericanIndian_AlaskaNative,Avg_PercentAsian,...,Avg_UnemploymentPct,Avg_PercentOfIndividualsBelow200PctFederalPovertyLinePctile,Avg_PercentOfIndividualsBelow200PctFederalPovertyLine,Avg_PercentOfIndividualsLt10oPctFederalPovertyLinePctile,Avg_PercentOfIndividualsLt100PctFederalPovertyLine,Avg_PercentIndividualsAge25OrOverWithLessThanHighSchoolDegreePct,Avg_PercentIndividualsAge25OrOverWithLessThanHighSchoolDegree,Avg_PercentOfResidentsWhoAreNotCurrentlyEnrolledInHigherEd,Avg_UnemploymentPctIn2009IslandAnd2010StatesAndPR,Avg_PercentageHouseholdsBelow100PctOfFederalPovertyLineIn2009Isl
0,1,31,39,31039,Cuming,41.915865,-96.788517,0.000000,0.000000,0.000000,...,2.333333,43.666667,27.000000,29.000000,6.666667,49.000000,10.333333,95.333333,1.333333,11.333333
1,2,53,69,53069,Wahkiakum,46.294638,-123.424458,0.010000,0.000000,0.010000,...,7.000000,39.000000,25.000000,30.000000,7.000000,40.000000,7.000000,96.000000,7.000000,12.000000
2,3,35,11,35011,De Baca,34.359273,-104.368696,0.010000,0.000000,0.000000,...,10.000000,81.000000,50.000000,64.000000,16.000000,70.000000,15.000000,96.000000,0.000000,21.000000
3,4,31,109,31109,Lancaster,40.783547,-96.688658,0.040811,0.005000,0.040541,...,2.816901,45.732394,31.112676,46.774648,13.929577,30.729730,6.662162,84.608108,4.041667,15.876712
4,5,31,129,31129,Nuckolls,40.176492,-98.046842,0.000000,0.000000,0.015000,...,1.000000,60.000000,35.500000,45.500000,10.500000,39.500000,7.500000,96.500000,2.500000,17.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3228,3229,13,123,13123,Gilmer,34.690506,-84.454624,0.004000,0.008000,0.002000,...,3.800000,61.400000,36.600000,62.200000,15.800000,73.400000,17.200000,96.400000,6.000000,16.400000
3229,3230,27,135,27135,Roseau,48.761068,-95.821504,0.010000,0.010000,0.018000,...,2.200000,38.600000,24.600000,34.200000,7.800000,34.400000,6.400000,96.400000,3.000000,9.600000
3230,3231,28,89,28089,Madison,32.634370,-90.034160,0.394762,0.000476,0.026667,...,4.857143,38.714286,26.476190,34.666667,9.761905,38.428571,9.000000,91.238095,4.619048,13.857143
3231,3232,48,227,48227,Howard,32.303471,-101.438772,0.045000,0.008000,0.002000,...,6.500000,59.800000,37.700000,59.600000,18.100000,73.600000,19.100000,95.400000,5.700000,17.700000
3232,3233,54,99,54099,Wayne,38.143642,-82.422666,0.009091,0.000909,0.003636,...,5.909091,73.545455,46.454545,78.545455,23.636364,73.636364,19.909091,94.181818,4.818182,19.636364

In [3]:
df = pd.read_csv("data/CtyAvTemp62016.csv", delimiter=',', skiprows=0, low_memory=False)
cityavgtmp_gdf = geopandas.GeoDataFrame(df)
cityavgtmp_gdf["TempFarenheit"] = 1.8*(cityavgtmp_gdf["TempK"]-273)+32
demo_gdf=geopandas.GeoDataFrame(pd.read_csv("CtyAvDemog2010.csv",delimiter=',', skiprows=0, low_memory=False, encoding='latin-1'))
merged_demo_cityavgtmp_gdf=demo_gdf.merge(cityavgtmp_gdf, how='inner', left_on="GEOID", right_on="GEOID")


merged_demo_cityavgtmp_gdf = geopandas.GeoDataFrame(
    merged_demo_cityavgtmp_gdf, 
    geometry=geopandas.points_from_xy(merged_demo_cityavgtmp_gdf["Lon_x"],
                                      merged_demo_cityavgtmp_gdf["Lat_x"]),
    crs="EPSG:4326"
)

merged_demo_cityavgtmp_gdf

,OBJECTID,STATEFP_x,COUNTYFP_x,GEOID,NAME_x,Lat_x,Lon_x,Avg_PercentBlackorAfricanAmericanalone,Avg_PercentAmericanIndian_AlaskaNative,Avg_PercentAsian,...,OBJECTID_1,STATEFP_y,COUNTYFP_y,NAME_y,Lat_y,Lon_y,Date_,TempK,TempFarenheit,geometry
0,1,31,39,31039,Cuming,41.915865,-96.788517,0.000000,0.000000,0.000000,...,551,31,39,Cuming,41.915865,-96.788517,6/20/2016 0:00,296.750000,74.750000,POINT (-96.78852 41.91587)
1,2,53,69,53069,Wahkiakum,46.294638,-123.424458,0.010000,0.000000,0.010000,...,96,53,69,Wahkiakum,46.294638,-123.424458,6/20/2016 0:00,289.850006,62.330011,POINT (-123.42446 46.29464)
2,3,35,11,35011,De Baca,34.359273,-104.368696,0.010000,0.000000,0.000000,...,2100,35,11,De Baca,34.359273,-104.368696,6/20/2016 0:00,299.049988,78.889978,POINT (-104.36870 34.35927)
3,4,31,109,31109,Lancaster,40.783547,-96.688658,0.040811,0.005000,0.040541,...,856,31,109,Lancaster,40.783547,-96.688658,6/20/2016 0:00,299.500000,79.700000,POINT (-96.68866 40.78355)
4,5,31,129,31129,Nuckolls,40.176492,-98.046842,0.000000,0.000000,0.015000,...,857,31,129,Nuckolls,40.176492,-98.046842,6/20/2016 0:00,299.500000,79.700000,POINT (-98.04684 40.17649)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3228,3229,13,123,13123,Gilmer,34.690506,-84.454624,0.004000,0.008000,0.002000,...,2329,13,123,Gilmer,34.690506,-84.454624,6/20/2016 0:00,294.875000,71.375000,POINT (-84.45462 34.69051)
3229,3230,27,135,27135,Roseau,48.761068,-95.821504,0.010000,0.010000,0.018000,...,92,27,135,Roseau,48.761068,-95.821504,6/20/2016 0:00,289.450012,61.610022,POINT (-95.82150 48.76107)
3230,3231,28,89,28089,Madison,32.634370,-90.034160,0.394762,0.000476,0.026667,...,2586,28,89,Madison,32.634370,-90.034160,6/20/2016 0:00,297.350006,75.830011,POINT (-90.03416 32.63437)
3231,3232,48,227,48227,Howard,32.303471,-101.438772,0.045000,0.008000,0.002000,...,2766,48,227,Howard,32.303471,-101.438772,6/20/2016 0:00,300.250000,81.050000,POINT (-101.43877 32.30347)
3232,3233,54,99,54099,Wayne,38.143642,-82.422666,0.009091,0.000909,0.003636,...,1519,54,99,Wayne,38.143642,-82.422666,6/20/2016 0:00,295.350037,72.230066,POINT (-82.42267 38.14364)

In [4]:
# making a choropleth map of us counties
uscounties_polygons_gdf = geopandas.read_file('https://raw.githubusercontent.com/holtzy/The-Python-Graph-Gallery/master/static/data/US-counties.geojson')
uscounties_polygons_gdf["id"] = uscounties_polygons_gdf["id"].astype(str).astype(np.int64)
uscounties_polygons_gdf = uscounties_polygons_gdf.rename(columns={"id":"FIPS_Code"})
uscounties_polygons_gdf

,FIPS_Code,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,1001,0500000US01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.71790 32.402..."
1,1009,0500000US01009,01,009,Blount,County,644.776,"POLYGON ((-86.57780 33.76532, -86.75914 33.840..."
2,1017,0500000US01017,01,017,Chambers,County,596.531,"POLYGON ((-85.18413 32.87053, -85.12342 32.772..."
3,1021,0500000US01021,01,021,Chilton,County,692.854,"POLYGON ((-86.51734 33.02057, -86.51596 32.929..."
4,1033,0500000US01033,01,033,Colbert,County,592.619,"POLYGON ((-88.13999 34.58170, -88.13925 34.587..."
...,...,...,...,...,...,...,...,...
3216,51001,0500000US51001,51,001,Accomack,County,449.496,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ..."
3217,51021,0500000US51021,51,021,Bland,County,357.725,"POLYGON ((-81.22510 37.23487, -81.20477 37.243..."
3218,51027,0500000US51027,51,027,Buchanan,County,502.763,"POLYGON ((-81.96830 37.53780, -81.92787 37.512..."
3219,51037,0500000US51037,51,037,Charlotte,County,475.271,"POLYGON ((-78.44332 37.07940, -78.49303 36.891..."
3220,51041,0500000US51041,51,041,Chesterfield,County,423.297,"POLYGON ((-77.85180 37.35487, -77.85515 37.418..."

In [5]:
# sjoin is one way to merge. This merges the two gdfs based on the geometry columns of the two gdfs
# and how the geometries intersect with each other
# (in the below case, the geometry in merged_medicare_cityavgtmp_gdf are latitude/longitude
# points, and in uscounties_polygons_gdf they are polygons representing us county shapes)
uscounties_gdf = uscounties_polygons_gdf.sjoin(merged_demo_cityavgtmp_gdf, how='inner', predicate="contains")

In [6]:
# Load packages for explore() function
pip install folium matplotlib mapclassify

SyntaxError: invalid syntax (<ipython-input-6-51a0c96b655a>, line 2)

In [ ]:
# Plot Energy Burden across the US
uscounties_gdf.explore(column="Avg_EnergyBurdenPct", tooltip=["NAME","COUNTY","STATE", "Avg_EnergyBurden", "Avg_EnergyBurdenPct"])

In [ ]:
# Plot Energy Burden across the US
uscounties_gdf.explore(column="Avg_PercentOfIndividualsBelow200PctFederalPovertyLine", tooltip=["NAME","COUNTY","STATE", "Avg_EnergyBurden", "Avg_EnergyBurdenPct", "Avg_TotalPopulation"])

### Exercise To Tackle the Big Questions 

Remember the Big Questions from the beginning of the notebook? This exercise will help you start to tackle 4 of them! 

Using the "CtyAvDemog2010.csv" dataset, 
1. Find the average and mean power outage over the time from June 19-June 22, 2016 for all of the Counties in the US using the Eagle-I data. 

2. Merge the data you get for mean and median outages per day with the data in CtyAvDemog2010.csv. You'll need to use the fips code the Eagle-I data and Geo-ID in the demographic data to match the data frames. 

3. Create a choropleth map to visualize the average number of power outages across the US. 

4. Which counties have the highest number of power outages? 

5. Create a choropleth map to visualize the average energy burden across the US. 

6. Can you identify any patterns in energy burden across the various geographical regions?


Note: You do not have to tackle the Big Questions with these exercises if you have an another plan in mind to work with. These are here to help you get started and are not mandatory.